apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapps
  namespace: default
  labels:
    app: myapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapps
  template:
    metadata:
      labels:
        app: myapps
    spec:
      containers:
      - name: myapps
        image: aksss.azurecr.io/kube:1.0.0
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: kube
